# Generated by Django 3.1 on 2020-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200721_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='', max_length=80)),
                ('price', models.FloatField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
