# Generated by Django 3.1 on 2020-08-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20200807_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyCarehome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DateField()),
                ('total', models.IntegerField()),
                ('covid', models.IntegerField()),
                ('t2018', models.FloatField()),
                ('t2017', models.FloatField()),
                ('t2016', models.FloatField()),
                ('t2015', models.FloatField()),
            ],
        ),
    ]
