# Generated by Django 3.1 on 2020-08-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_weeklycarehome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklycarehome',
            old_name='week',
            new_name='Week',
        ),
    ]
